spring:
  application:
    name: demo
  profiles:
    active: dev  # Cambia a "prod" en producción

  datasource:
    url: jdbc:h2:file:./demoDb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    generate-ddl: true
    open-in-view: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true

server:
  servlet:
    context-path: /demo

logging:
  level:
    web: debug
